#!/bin/bash
# Install or remove the Neon Saturn window behavior:
#   - every theme: windows fully opaque, no dimming of unfocused windows, and GTK
#     apps recoloured from the active theme and never repainted on focus loss;
#   - Neon Saturn only: violet glow on the focused window, animated gradient
#     border, tight gaps, 4px rounding, blur and slide animations.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: install.sh [--no-gtk] | --uninstall | --help

  (no option)   Install the window behavior, or refresh an earlier install.
  --no-gtk      Install only the Hyprland part; leave GTK apps untouched.
  --uninstall   Remove everything this script installed and restore what it replaced.
EOF
}

MODE=install
GTK=1
for arg in "$@"; do
  case "$arg" in
    --uninstall) MODE=uninstall ;;
    --no-gtk) GTK=0 ;;
    -h | --help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done

SRC=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# Omarchy itself uses these fixed locations, whatever the XDG variables say.
CONFIG_HOME="$HOME/.config"
STATE_HOME="$HOME/.local/state"
OMARCHY_PATH="${OMARCHY_PATH:-/usr/share/omarchy}"

HYPR_MAIN="$CONFIG_HOME/hypr/hyprland.lua"
HYPR_FILE="$CONFIG_HOME/hypr/neon-saturn.lua"
HOOK_DIR="$CONFIG_HOME/omarchy/hooks/theme-set.d"
HOOKS=(neon-saturn-gtk neon-saturn-gtk-accent)
GTK_FILES=("$CONFIG_HOME/gtk-3.0/gtk.css" "$CONFIG_HOME/gtk-4.0/gtk.css")
MARK="/* omarchy-neon-saturn: generated by the window-behavior extra, safe to delete */"
STATE="$STATE_HOME/omarchy-neon-saturn"
BLOCK_START="-- >>> omarchy-neon-saturn window behavior (remove with extras/window-behavior/install.sh --uninstall)"
BLOCK_END="-- <<< omarchy-neon-saturn window behavior"

say() { printf '%s\n' "$*"; }
die() { printf 'install.sh: %s\n' "$*" >&2; exit 1; }

# Omarchy 4 configures Hyprland in Lua; older releases used hyprland.conf.
[[ -f $HYPR_MAIN ]] || die "$HYPR_MAIN not found. This extra needs Omarchy 4 or later (Lua Hyprland config)."
[[ -f $OMARCHY_PATH/default/hypr/paths.lua ]] || die "$OMARCHY_PATH/default/hypr/paths.lua not found. This extra needs Omarchy 4 or later."

BACKUP=""
backup() {
  local path="$1" rel
  [[ -e $path || -L $path ]] || return 0
  if [[ -z $BACKUP ]]; then
    mkdir -p "$CONFIG_HOME/omarchy/backups"
    BACKUP=$(mktemp -d "$CONFIG_HOME/omarchy/backups/$(date -u +%Y%m%dT%H%M%SZ)-neon-saturn.XXXX")
  fi
  rel=${path#"$HOME"/}
  mkdir -p "$BACKUP/$(dirname -- "$rel")"
  cp -P -p -- "$path" "$BACKUP/$rel"
}

has_block() {
  grep -qxF -- "$BLOCK_START" "$HYPR_MAIN"
}

# Drops the marked block and the blank line written in front of it.
strip_block() {
  local tmp
  tmp=$(mktemp)
  awk -v start="$BLOCK_START" -v end="$BLOCK_END" '
    $0 == start { skip = 1; held = 0; next }
    skip { if ($0 == end) skip = 0; next }
    held { print ""; held = 0 }
    $0 == "" { held = 1; next }
    { print }
    END { if (held) print "" }
  ' "$HYPR_MAIN" >"$tmp"
  cat "$tmp" >"$HYPR_MAIN"
  rm -f "$tmp"
}

hypr_running() {
  command -v hyprctl >/dev/null 2>&1 && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]
}

hypr_errors() {
  hyprctl configerrors 2>/dev/null | grep -v '^[[:space:]]*$' || true
}

active_theme() {
  cat "$STATE_HOME/omarchy/current/theme.name" 2>/dev/null || true
}

run_hooks() {
  local theme hook
  theme=$(active_theme)
  for hook in "${HOOKS[@]}"; do
    if [[ -x $HOOK_DIR/$hook ]]; then
      "$HOOK_DIR/$hook" "$theme" >/dev/null || true
    fi
  done
}

install_hypr() {
  local before="" errors
  hypr_running && before=$(hypr_errors)
  backup "$HYPR_MAIN"
  backup "$HYPR_FILE"
  install -Dm644 "$SRC/hypr/neon-saturn.lua" "$HYPR_FILE"

  if ! has_block; then
    [[ -z $(tail -c1 "$HYPR_MAIN") ]] || printf '\n' >>"$HYPR_MAIN"
    printf '\n%s\nrequire("hypr.neon-saturn")\n%s\n' "$BLOCK_START" "$BLOCK_END" >>"$HYPR_MAIN"
  fi

  if hypr_running; then
    hyprctl reload >/dev/null
    errors=$(hypr_errors)
    if [[ -n $errors && $errors != "$before" ]]; then
      say "Hyprland reported config errors; rolling back:" >&2
      say "$errors" >&2
      strip_block
      rm -f "$HYPR_FILE"
      hyprctl reload >/dev/null
      exit 1
    fi
  fi
  say "Hyprland: installed $HYPR_FILE and loaded it from $HYPR_MAIN"
}

install_gtk() {
  local f
  mkdir -p "$STATE" "$HOOK_DIR"

  # Remember the accent to restore for other themes and on uninstall.
  if [[ ! -f $STATE/accent-color ]] && command -v gsettings >/dev/null 2>&1; then
    gsettings get org.gnome.desktop.interface accent-color 2>/dev/null | tr -d "'" >"$STATE/accent-color" || true
  fi

  # A gtk.css the user wrote is set aside, and put back on uninstall.
  for f in "${GTK_FILES[@]}"; do
    if [[ -L $f ]] || { [[ -f $f ]] && ! head -1 "$f" | grep -qF "$MARK"; }; then
      backup "$f"
      printf '%s\t%s\n' "$f" "$BACKUP/${f#"$HOME"/}" >>"$STATE/moved-gtk-css"
      rm -f -- "$f"
      say "GTK: moved your $f to $BACKUP"
    fi
  done

  for f in "${HOOKS[@]}"; do
    install -Dm755 "$SRC/hooks/$f" "$HOOK_DIR/$f"
  done
  run_hooks
  say "GTK: installed theme-set hooks in $HOOK_DIR (restart open GTK apps to pick them up)"
}

uninstall() {
  local f saved dest from
  if has_block; then
    backup "$HYPR_MAIN"
    strip_block
  fi
  rm -f "$HYPR_FILE"
  if hypr_running; then
    hyprctl reload >/dev/null || true
  fi
  say "Hyprland: removed the window behavior"

  for f in "${HOOKS[@]}"; do
    rm -f "$HOOK_DIR/$f"
  done
  for f in "${GTK_FILES[@]}"; do
    [[ -f $f && ! -L $f ]] && head -1 "$f" | grep -qF "$MARK" && rm -f -- "$f"
  done
  rm -f "$CONFIG_HOME/gtk-3.0/adwaita-no-backdrop.css"

  # Newest backup first, so a file set aside twice comes back as it was last.
  if [[ -f $STATE/moved-gtk-css ]]; then
    while IFS=$'\t' read -r dest from; do
      if [[ (-e $from || -L $from) && ! -e $dest && ! -L $dest ]]; then
        mkdir -p "$(dirname -- "$dest")"
        cp -P -p -- "$from" "$dest"
        say "GTK: restored $dest"
      fi
    done < <(tac "$STATE/moved-gtk-css")
  fi

  saved=$(cat "$STATE/accent-color" 2>/dev/null || true)
  if [[ -n $saved ]] && command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface accent-color "$saved" 2>/dev/null || true
  fi
  rm -rf -- "$STATE"
  say "GTK: removed the hooks and generated stylesheets (restart open GTK apps)"
}

if [[ $MODE == uninstall ]]; then
  uninstall
else
  install_hypr
  if (( GTK )); then
    install_gtk
  fi
  [[ -d $CONFIG_HOME/omarchy/themes/neon-saturn || -d $OMARCHY_PATH/themes/neon-saturn ]] ||
    say "Note: the Neon Saturn theme itself is not installed; its glow applies once it is the active theme."
fi
[[ -z $BACKUP ]] || say "Backups: $BACKUP"
